import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import type { Edge, Node } from "@xyflow/react";
import type { Scene } from "./types";
import { CABLE_COLORS } from "./types";
import { DB } from "./equipmentDB";
import type { EquipmentModelId } from "./equipmentDB";
import { BATTERY_DB } from "./batteryDB";
import { calcRuntime, DEFAULT_BATTERY, type BatterySelection } from "./BatterySection";

// A4 landscape: 297mm × 210mm → 1122 × 794px at 96dpi
const PAGE_W = 1122;
const PAGE_H = 794;
const FONT = "'Yu Gothic', 'Hiragino Kaku Gothic ProN', 'MS PGothic', -apple-system, sans-serif";

function esc(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function fmtDate(dateStr: string): string {
  if (!dateStr) return new Date().toLocaleDateString("ja-JP");
  try { return new Date(dateStr).toLocaleDateString("ja-JP"); }
  catch { return dateStr; }
}

function getNodeName(nodeId: string, nodes: Node[]): string {
  const node = nodes.find(n => n.id === nodeId);
  const eq = node?.data?.equipment as { name?: string } | undefined;
  return eq?.name ?? nodeId;
}

function makePageDiv(innerHTML: string): HTMLDivElement {
  const div = document.createElement("div");
  div.style.cssText = [
    `width:${PAGE_W}px`,
    `height:${PAGE_H}px`,
    "background:#FFFFFF",
    "position:relative",
    `font-family:${FONT}`,
    "overflow:hidden",
    "box-sizing:border-box",
  ].join(";");
  div.innerHTML = innerHTML;
  return div;
}

function footer(pageNum: number): string {
  return `
    <div style="position:absolute;bottom:0;left:0;right:0;height:28px;
      display:flex;align-items:center;padding:0 36px;
      border-top:1px solid rgba(0,0,0,0.08);">
      <span style="font-size:11px;color:#86868b;">Generated by CineRig</span>
      <span style="flex:1;"></span>
      <span style="font-size:11px;color:#86868b;">${pageNum}</span>
    </div>`;
}

// ── Page 1: header + diagram ───────────────────────────────────────────────

function buildPage1(
  diagramDataUrl: string,
  meta: { name: string; author: string; date: string },
): HTMLDivElement {
  const HEADER_H = 56;
  const FOOTER_H = 28;
  const gap = 8;
  const diagramH = Math.round((PAGE_H - HEADER_H - FOOTER_H - gap * 2) * 0.72);

  const html = `
    <div style="position:absolute;top:0;left:0;right:0;height:${HEADER_H}px;
      display:flex;align-items:center;padding:0 36px;
      border-bottom:1px solid rgba(0,0,0,0.08);">
      <div>
        <div style="font-size:22px;font-weight:700;color:#1d1d1f;letter-spacing:-0.5px;">CineRig</div>
      </div>
      <div style="flex:1;"></div>
      <div style="text-align:right;">
        <div style="font-size:15px;font-weight:600;color:#1d1d1f;">${esc(meta.name)}</div>
        ${meta.author ? `<div style="font-size:11px;color:#6e6e73;margin-top:3px;">担当: ${esc(meta.author)}</div>` : ""}
        <div style="font-size:11px;color:#86868b;margin-top:3px;">${fmtDate(meta.date)}</div>
      </div>
    </div>

    <div style="position:absolute;top:${HEADER_H + gap}px;left:36px;right:36px;
      height:${diagramH}px;background:#FAFAFA;border-radius:8px;overflow:hidden;
      border:1px solid rgba(0,0,0,0.07);">
      <img src="${diagramDataUrl}"
        style="width:100%;height:100%;object-fit:contain;" />
    </div>

    ${footer(1)}`;

  return makePageDiv(html);
}

// ── Page 2: cable list + battery ───────────────────────────────────────────

function buildPage2(
  edges: Edge[],
  nodes: Node[],
  scene: Scene,
  batterySelections: Record<string, BatterySelection>,
): HTMLDivElement {
  const HEADER_H = 44;
  const FOOTER_H = 28;
  const contentY = HEADER_H + 8;
  const contentH = PAGE_H - contentY - FOOTER_H - 8;

  // ── Cable table ────────────────────────────────────────────────────────────
  const cableEdges = edges.filter(
    e => e.data?.cableType && e.data.cableType !== "WIRELESS",
  );

  const cableRows = cableEdges.map((edge, i) => {
    const from = esc(getNodeName(edge.source, nodes));
    const to   = esc(getNodeName(edge.target, nodes));
    const ct   = (edge.data?.cableType as string) ?? "—";
    const color = CABLE_COLORS[ct] ?? "#6b7280";
    const bg    = i % 2 === 0 ? "#FFFFFF" : "#F5F5F7";
    return `
      <tr style="background:${bg};">
        <td style="padding:5px 8px;font-size:11px;color:#86868b;">${i + 1}</td>
        <td style="padding:5px 8px;">
          <span style="font-size:11px;font-weight:600;color:${color};">${esc(ct)}</span>
        </td>
        <td style="padding:5px 8px;font-size:11px;color:#1d1d1f;">${from}</td>
        <td style="padding:5px 8px;font-size:11px;color:#1d1d1f;">${to}</td>
      </tr>`;
  }).join("");

  const cableSection = cableEdges.length === 0
    ? `<span style="font-size:12px;color:#86868b;">ケーブルなし</span>`
    : `<table style="width:100%;border-collapse:collapse;">
        <thead>
          <tr>
            ${["#", "種類", "From", "To"].map(h =>
              `<th style="padding:4px 8px;font-size:10px;font-weight:700;color:#86868b;
                text-align:left;border-bottom:1px solid rgba(0,0,0,0.08);">${h}</th>`
            ).join("")}
          </tr>
        </thead>
        <tbody>${cableRows}</tbody>
      </table>`;

  // ── Battery ────────────────────────────────────────────────────────────────
  const cameraRows = scene.cameras.map(cam => {
    const camWatts = DB[cam.model as EquipmentModelId]?.richSpec?.powerConsumption ?? null;
    const onboardMons = scene.monitors.filter(m =>
      m.role === "onboard" &&
      (m.cameraId === cam.id || (!m.cameraId && scene.cameras.length === 1))
    );
    const txSets = scene.wirelessSets.filter(ws => ws.sourceId === cam.id);
    const parts: (number | null)[] = [
      camWatts,
      ...onboardMons.map(m => DB[m.model as EquipmentModelId]?.richSpec?.powerConsumption ?? null),
      ...txSets.map(ws =>
        DB[(ws.txModel ?? "wireless_tx") as EquipmentModelId]?.richSpec?.powerConsumption ?? null
      ),
    ];
    const totalWatts: number | null = parts.some(p => p === null)
      ? null
      : (parts.reduce<number>((s, p) => s + (p ?? 0), 0));
    return {
      entityId: cam.id,
      label: DB[cam.model as EquipmentModelId]?.name ?? cam.model,
      watts: totalWatts,
    };
  });

  const monitorRows = scene.monitors
    .filter(m => m.role !== "onboard")
    .map(mon => ({
      entityId: mon.id,
      label: DB[mon.model as EquipmentModelId]?.name ?? mon.model,
      watts: DB[mon.model as EquipmentModelId]?.richSpec?.powerConsumption ?? null,
    }));

  function batteryRowHtml(row: { entityId: string; label: string; watts: number | null }): string {
    const sel = batterySelections[row.entityId] ?? DEFAULT_BATTERY;
    const battery = BATTERY_DB[sel.batteryId];
    const hours = battery && row.watts !== null && row.watts > 0
      ? calcRuntime(sel.batteryId, sel.count, row.watts)
      : null;
    const hColor = hours === null ? "#86868b" : hours < 2 ? "#E24B4A" : hours < 4 ? "#EF9F27" : "#639922";
    return `
      <div style="background:#F5F5F7;border-radius:6px;padding:7px 10px;
        display:flex;align-items:center;gap:8px;margin-bottom:5px;">
        <div style="flex:1;min-width:0;">
          <div style="font-size:11px;font-weight:600;color:#1d1d1f;
            white-space:nowrap;overflow:hidden;text-overflow:ellipsis;">
            ${esc(row.label)}
          </div>
          <div style="font-size:10px;color:#86868b;">
            ${row.watts !== null ? `${row.watts}W` : "消費電力不明"}
          </div>
        </div>
        <div style="font-size:10px;color:#6e6e73;white-space:nowrap;">
          ${esc(battery?.model ?? "—")} ×${sel.count}
        </div>
        <div style="font-size:12px;font-weight:700;color:${hColor};
          white-space:nowrap;min-width:38px;text-align:right;">
          ${hours !== null ? `${hours.toFixed(1)}h` : "—"}
        </div>
      </div>`;
  }

  const tally: Record<string, number> = {};
  for (const row of [...cameraRows, ...monitorRows]) {
    const sel = batterySelections[row.entityId] ?? DEFAULT_BATTERY;
    tally[sel.batteryId] = (tally[sel.batteryId] ?? 0) + sel.count;
  }

  const tallyItems = Object.entries(tally)
    .map(([id, cnt]) => `${esc(BATTERY_DB[id]?.model ?? id)} ×${cnt}本`)
    .join("&emsp;");

  const batterySection = `
    ${cameraRows.length > 0 ? `
      <div style="font-size:10px;font-weight:700;color:#86868b;letter-spacing:1px;
        margin-bottom:6px;">カメラグループ</div>
      ${cameraRows.map(batteryRowHtml).join("")}` : ""}
    ${monitorRows.length > 0 ? `
      <div style="font-size:10px;font-weight:700;color:#86868b;letter-spacing:1px;
        margin:10px 0 6px;">モニター（独立電源）</div>
      ${monitorRows.map(batteryRowHtml).join("")}` : ""}
    ${tallyItems ? `
      <div style="background:#E6F0FA;border-radius:8px;padding:8px 12px;margin-top:10px;">
        <span style="font-size:11px;font-weight:600;color:#005BA6;">合計必要本数: </span>
        <span style="font-size:11px;color:#005BA6;">${tallyItems}</span>
      </div>` : ""}`;

  const html = `
    <div style="position:absolute;top:0;left:0;right:0;height:${HEADER_H}px;
      display:flex;align-items:center;padding:0 36px;
      border-bottom:1px solid rgba(0,0,0,0.08);">
      <span style="font-size:20px;font-weight:700;color:#1d1d1f;letter-spacing:-0.5px;">CineRig</span>
      <div style="flex:1;"></div>
      <span style="font-size:12px;color:#86868b;">機材計算書</span>
    </div>

    <div style="position:absolute;top:${contentY}px;left:36px;right:36px;
      height:${contentH}px;display:flex;gap:16px;overflow:hidden;">

      <div style="flex:1;overflow:hidden;">
        <div style="font-size:10px;font-weight:700;color:#86868b;letter-spacing:1.2px;
          margin-bottom:8px;">CABLE LIST</div>
        ${cableSection}
      </div>

      <div style="width:1px;background:rgba(0,0,0,0.08);flex-shrink:0;"></div>

      <div style="flex:1;overflow:hidden;">
        <div style="font-size:10px;font-weight:700;color:#86868b;letter-spacing:1.2px;
          margin-bottom:8px;">BATTERY</div>
        ${batterySection}
      </div>
    </div>

    ${footer(2)}`;

  return makePageDiv(html);
}

// ── Main export function ───────────────────────────────────────────────────

export async function exportPdf(
  reactFlowEl: HTMLElement,
  meta: { name: string; author: string; date: string },
  edges: Edge[],
  nodes: Node[],
  scene: Scene,
  batterySelections: Record<string, BatterySelection>,
): Promise<void> {
  // 1. Capture the ReactFlow diagram
  const diagramCanvas = await html2canvas(reactFlowEl, {
    backgroundColor: "#FAFAFA",
    scale: 2,
    useCORS: true,
    allowTaint: true,
    logging: false,
  });
  const diagramDataUrl = diagramCanvas.toDataURL("image/png");

  // 2. Build page HTML divs off-screen
  const page1Div = buildPage1(diagramDataUrl, meta);
  const page2Div = buildPage2(edges, nodes, scene, batterySelections);

  const container = document.createElement("div");
  container.style.cssText =
    "position:absolute;top:-9999px;left:-9999px;width:auto;height:auto;pointer-events:none;";
  document.body.appendChild(container);

  try {
    container.appendChild(page1Div);
    container.appendChild(page2Div);

    // 3. Capture each page
    const opts = { scale: 2, backgroundColor: "#FFFFFF", logging: false } as const;
    const [p1, p2] = await Promise.all([
      html2canvas(page1Div, opts),
      html2canvas(page2Div, opts),
    ]);

    // 4. Assemble PDF
    const pdf = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
    pdf.addImage(p1.toDataURL("image/png"), "PNG", 0, 0, 297, 210);
    pdf.addPage();
    pdf.addImage(p2.toDataURL("image/png"), "PNG", 0, 0, 297, 210);

    const safeName = (meta.name || "CineRig").replace(/[/\\:*?"<>|]/g, "_");
    pdf.save(`${safeName}_${new Date().toISOString().slice(0, 10)}.pdf`);
  } finally {
    document.body.removeChild(container);
  }
}
